### ISSUE TITLE
Input `...`

### ISSUE THREAD

**Issue by ray-x** [nickeb96/puffer-fish#11]
in some cases I need to input `...` , e.g.  `go test ./...`
I am wondering is that possible?

**Comment by nickeb96** [comment]
A feature was added by [this pull request](https://github.com/nickeb96/puffer-fish/pull/1) a couple years ago that prevents `..` from being expanded on a path that starts with `./`.

I'm pretty sure this would have solved your issue.

**Comment by ray-x** [comment]
not perfect but works fine.
It prevents me from running `go test ...` though
