### ISSUE TITLE
versioned releases

### ISSUE THREAD

**Issue by quantenzitrone** [nickeb96/puffer-fish#13]
I am the maintainer of this package in nixpkgs, and it would be nice if you could create a tag every time you think release-worthy features, critical bugs or generally enough small changes have been made.
I would subscribe to the tag RSS feed and then update the package. The package could also be auto-updated.
It would make maintaining significantly easier, because if I wanted to keep the package up to date without, I would need to either subscribe to every commit or regularly remember to look manually if anything significant has happened.

**Comment by nickeb96** [comment]
Sure thing, I'll start tagging when I add/fix something.

I just created a v1.0.0 tag from the HEAD commit.  It's a lightweight git tag, will that work for you?

**Comment by quantenzitrone** [comment]
Yep, thanks!
