### ISSUE TITLE
$$ command not working 

### ISSUE THREAD

**Issue by REIS0** [nickeb96/puffer-fish#2]
The `$$` commando does not work at all, while `...` and `....` work without any problems.

![ezgif-6-6a4d461789b8](https://user-images.githubusercontent.com/38042161/94869559-1c545a00-0435-11eb-8f13-37803850a97d.gif)

Using fish with alacritty and these plugins
![image](https://user-images.githubusercontent.com/38042161/94869614-39892880-0435-11eb-9dba-c7cd3319cc90.png)

**Comment by nickeb96** [comment]
Yes, I made a mistake when I was writing up the documentation.  It's actually `sudo !!`, not `sudo $$`.  I updated the readme a little while ago when I caught it.  Sorry for the confusion.

**Comment by REIS0** [comment]
oh that was only it, well we can call it fixed
